name: WFGY-CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest      #  Linux runners
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      
      - run: pip install -e ".[dev]"      

      
      - run: python tests/test_sdk_full.py
